### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by swade1987** [yannh/kubernetes-json-schema#8]
I am getting the following error when trying to run `build.sh` 

```
+ docker run -i -v<redacted>:/out/schemas ghcr.io/yannh/openapi2jsonschema:latest -o schemas/v1.15.0-standalone-strict --expanded --kubernetes --stand-alone --strict https://raw.githubusercontent.com/kubernetes/kubernetes/v1.15.0/api/openapi-spec/swagger.json
Downloading schema
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/urllib/request.py", line 1342, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/usr/local/lib/python3.9/http/client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)
```

**Comment by yannh** [comment]
Hi @swade1987 , quite frankly not too sure what to tell you, that exact command you posted works both in CI and on my machine, and in theory docker should help making sure this works everywhere... is it possible you have some proxy that would intercept the request? It seems to complain about an incorrect SSL certificate.

**Comment by swade1987** [comment]
Indeed that was the issue, the corp proxy on my work laptop was blocking the connections, using my personal laptop it worked fine. Closing the issue.
